### ISSUE TITLE
Option to have output path relative to project root

### ISSUE THREAD

**Issue by rayshan** [unindented/stats-webpack-plugin#4]
Currently output path seems to be relative to webpack config's `output.path`. I tried to use something like `/Users/rayshan/...` to be relative to user root but it didn't work. So I'm resorting to `../../../_debug/webpackStats.json` to be relative to project root, but this is fragile. Can we please have an option?

As a side note, in `readme.md`, `filename` argument should probably be named `outputPath`, as it's not just the file name.

**Comment by unindented** [comment]
See https://github.com/unindented/stats-webpack-plugin/pull/3#issuecomment-118409778. Using webpack's output API means the path will be relative to webpack's output folder. You can create a PR in webpack to allow for absolute paths, as suggested in the discussion.

I will make the `README` clearer though.

**Comment by unindented** [comment]
Done in https://github.com/unindented/stats-webpack-plugin/commit/e472aaec284aa22b9759b719da26e7c68e3cdd4e

**Comment by rayshan** [comment]
Ahh I see. Thanks Daniel.

**Comment by vyorkin** [comment]
sorry, but its still not clear that I can't use smth like `.../stats.json` as a path:
```
[14:34:20] [webpack]
                                            Asset       Size  Chunks             Chunk Names
                                      vendors.js     942 kB       0  [emitted]  vendors
                     app.0ceb0dab79b4bc432512.js    58.6 kB       1  [emitted]  app
        app.9947e855c46c3834b7c2d514c193b3cd.css    7.13 kB       1  [emitted]  app
    vendors.3534a568b27f279abbaa6b8b44722e89.css    87.3 kB       0  [emitted]  vendors
                                  vendors.js.map    8.27 MB       0  [emitted]  vendors
vendors.3534a568b27f279abbaa6b8b44722e89.css.map  121 bytes       0  [emitted]  vendors
                 app.0ceb0dab79b4bc432512.js.map     375 kB       1  [emitted]  app
    app.9947e855c46c3834b7c2d514c193b3cd.css.map  117 bytes       1  [emitted]  app
                           ../webpack.stats.json    0 bytes          [emitted]

```

**Comment by unindented** [comment]
@vyorkin Does it work any different if you specify `webpack.stats.json` as the path, instead of `../webpack.stats.json`?

**Comment by vyorkin** [comment]
@unindented Yes, it works well when its a path inside the output directory

**Comment by unindented** [comment]
@vyorkin I'm just using webpack's output API. Maybe file a ticket in that repo?

**Comment by vyorkin** [comment]
@unindented ok, I've just looked at the source, I'll fork & play with it, thanks!

**Comment by mnpenner** [comment]
To anyone else that stumbles across this, @vyorkin wrote a double negative; using a relative path (with `..`s) *does* work.

An easy way to create your desired path is using [`path.relative`](https://nodejs.org/api/path.html#path_path_relative_from_to), e.g:

```js
path.relative(publicAssetsDir, './webpack.stats.json') // -> ../../webpack.stats.json
```

**Comment by zdila** [comment]
With relative path I am getting this:
```
/home/martin/my-project/node_modules/webpack/lib/RequestShortener.js:8
	directory = directory.replace(/\\/g, "/");
	                      ^

TypeError: directory.replace is not a function
    at new RequestShortener (/home/martin/g/gruveo-html5/node_modules/webpack/lib/RequestShortener.js:8:24)
    at Stats.toJson (/home/martin/g/gruveo-html5/node_modules/webpack/lib/Stats.js:32:25)
    at Object.getSource [as source] (/home/martin/g/gruveo-html5/node_modules/stats-webpack-plugin/index.js:25:56)
    at Compiler.writeOut (/home/martin/g/gruveo-html5/node_modules/webpack/lib/Compiler.js:256:26)
    at /home/martin/g/gruveo-html5/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)
```
